[Variables]
; DevOps Config, see https://github.com/OfficerHalf/devops-rainmeter for more info

; DevOpsCoreServer=dev.azure.com
; DevOpsReleaseServer=vsrm.dev.azure.com
; DevOpsApiVersion="5.1"
; DevOpsUpdateRate=60

DevOpsAccessToken=
DevOpsOrganization=
DevOpsProject=
DevOpsRespository=
DevOpsUserId=
DevOpsBuildDefinition=
DevOpsReleaseDefinition=
DevOpsReleaseEnvironment=

; Font Config
; Defaults
; VFontSize=30
; VFontColor=255,255,255
; VFontColorSuccess=0,255,0
; VFontColorFailure=255,0,0
; VFontColorWorking=0,0,255
; VFontFace=Segoe UI

VFontSize=30
VFontColor=255,255,255
VFontColorSuccess=0,255,0
VFontColorFailure=255,0,0
VFontColorWorking=0,0,255
VFontFace=Segoe UI

; Enable / Disable skin elements
DisablePRIcon=0
DisablePRText=0
DisableBuildIcon=0
DisableBuildText=0
DisableReleaseIcon=0
DisableReleaseText=0